### ISSUE TITLE
Problem with init structure?

### ISSUE THREAD

**Issue by amverdo** [andrey-helldar/package-wizard#21]
- Package Wizard: 1.1.0 +
- Composer Version: 2.0.9
- PHP Version: 7.4.15 +
- OS version: Linux Mint 20.1 (Cinnamon)

### Description:
What's happening?  I getting this problem. I can't init package.

### Steps To Reproduce:

composer package:init
![Problem with init](https://i.imgur.com/6Mk7hEu.png)

**Comment by amverdo** [comment]
@andrey-helldar ?

**Comment by andrey-helldar** [comment]
Hm...

![image](https://user-images.githubusercontent.com/10347617/109519788-9fe5a600-7abc-11eb-8e5a-27c25628db28.png)

![image](https://user-images.githubusercontent.com/10347617/109519802-a411c380-7abc-11eb-86f0-22c9ca843ddd.png)

I will check shortly why this problem might occur.

**Comment by amverdo** [comment]
@andrey-helldar 
I think that problem may occur by some naming in OS (Linux Mint 20.1), maybe....
I don't try on Ubuntu.

**Comment by andrey-helldar** [comment]
![image](https://user-images.githubusercontent.com/10347617/109522722-9e69ad00-7abf-11eb-8b1a-a864d5b08356.png)

On, caught the problem.

I am developing for Windows. There are no problems on it.
Now launched on ubuntu in docker - there is a problem.
In the near future I will find and fix the cause of the error.

**Comment by amverdo** [comment]
@andrey-helldar Great! Ok.

**Comment by andrey-helldar** [comment]
@amverdo, an interesting moment - the error is not reproduced.

Try the commands:

```
$ composer self-update
$ composer global update
```

Then try again to execute the `composer package:init` command.

![image](https://user-images.githubusercontent.com/10347617/109624073-d53ad400-7b4e-11eb-8db0-b4c5a9bd48f1.png)

PHP: 7.4.15
Composer: 2.0.11
Package Wizard: 1.2.1

**Comment by amverdo** [comment]
> @amverdo, an interesting moment - the error is not reproduced.
> 
> Try the commands:
> 
> ```
> $ composer self-update
> $ composer global update
> ```
> 
> Then try again to execute the `composer package:init` command.
> 
> ![image](https://user-images.githubusercontent.com/10347617/109624073-d53ad400-7b4e-11eb-8db0-b4c5a9bd48f1.png)
> 
> PHP: 7.4.15
> Composer: 2.0.11
> Package Wizard: 1.2.1

Reproduced for me...

**Comment by amverdo** [comment]
I'm will trying on other OS, i think that true key of problem.

**Comment by andrey-helldar** [comment]
I am currently implementing debugging functionality. I will finish it in a few hours and we will be able to check at what point the error occurs.

**Comment by andrey-helldar** [comment]
Perhaps the problem was due to this moment:

![image](https://user-images.githubusercontent.com/10347617/109635177-218c1100-7b5b-11eb-98be-2a7e47166bd2.png)

![image](https://user-images.githubusercontent.com/10347617/109635192-25b82e80-7b5b-11eb-8894-493e2550b8df.png)

**Comment by andrey-helldar** [comment]
@amverdo, update the package to the latest version and run with the `-vvv` parameter:

```bash
$ composer global update
$ composer package:init -vvv
```

Write if you still have an error. If yes, please send a screenshot of the error.

**Comment by amverdo** [comment]
@andrey-helldar It's works! But without `src` directory in result. Thanks!

**Comment by andrey-helldar** [comment]
Fine. So, I fixed the error while looking for it :)

The directory is empty because I have not completely filled out the resource template (https://github.com/andrey-helldar/package-wizard/tree/main/resources/stubs).

I am currently busy moving resources to external repositories. Based on them, I will fill in templates for both the symphony and other projects :)

**Comment by amverdo** [comment]
> Fine. So, I fixed the error while looking for it 
> 
> The directory is empty because I have not completely filled out the [resource template](https://github.com/andrey-helldar/package-wizard/tree/main/resources/stubs).
> 
> I am currently busy moving resources to [external repositories](https://github.com/andrey-helldar/package-wizard-template). Based on them, I will fill in templates for both the symphony and other projects :)

And... "symfony" instead "symphony" :wink:

**Comment by andrey-helldar** [comment]
Sorry, Google translate 😀
